
package web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeSoap", targetNamespace = "http://web/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeSoap {


    /**
     * 
     * @return
     *     returns web.GroupOfEmployees
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://web/EmployeeSoap/readAllRequest", output = "http://web/EmployeeSoap/readAllResponse")
    public GroupOfEmployees readAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns web.Employee
     */
    @WebMethod
    @WebResult(name = "Employee", partName = "Employee")
    @Action(input = "http://web/EmployeeSoap/readByIdRequest", output = "http://web/EmployeeSoap/readByIdResponse")
    public Employee readById(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @param employee
     */
    @WebMethod
    @Action(input = "http://web/EmployeeSoap/insertEmployeeRequest", output = "http://web/EmployeeSoap/insertEmployeeResponse")
    public void insertEmployee(
        @WebParam(name = "Employee", partName = "Employee")
        Employee employee);

    /**
     * 
     * @param arg0
     * @return
     *     returns web.GroupOfEmployees
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://web/EmployeeSoap/readAllByPincodeRequest", output = "http://web/EmployeeSoap/readAllByPincodeResponse")
    public GroupOfEmployees readAllByPincode(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

}
