
package services.employee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeePort", targetNamespace = "http://employee.services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeePort {


    /**
     * 
     * @param saveRequest
     * @return
     *     returns services.employee.SaveResponse
     */
    @WebMethod
    @WebResult(name = "saveResponse", targetNamespace = "http://employee.services", partName = "saveResponse")
    public SaveResponse save(
        @WebParam(name = "saveRequest", targetNamespace = "http://employee.services", partName = "saveRequest")
        SaveRequest saveRequest);

    /**
     * 
     * @param findAllEmployeesRequest
     * @return
     *     returns services.employee.FindAllEmployeesResponse
     */
    @WebMethod
    @WebResult(name = "findAllEmployeesResponse", targetNamespace = "http://employee.services", partName = "findAllEmployeesResponse")
    public FindAllEmployeesResponse findAllEmployees(
        @WebParam(name = "findAllEmployeesRequest", targetNamespace = "http://employee.services", partName = "findAllEmployeesRequest")
        FindAllEmployeesRequest findAllEmployeesRequest);

    /**
     * 
     * @param findByPincodeRequest
     * @return
     *     returns services.employee.FindByPincodeResponse
     */
    @WebMethod
    @WebResult(name = "findByPincodeResponse", targetNamespace = "http://employee.services", partName = "findByPincodeResponse")
    public FindByPincodeResponse findByPincode(
        @WebParam(name = "findByPincodeRequest", targetNamespace = "http://employee.services", partName = "findByPincodeRequest")
        FindByPincodeRequest findByPincodeRequest);

    /**
     * 
     * @param findByIdRequest
     * @return
     *     returns services.employee.FindByIdResponse
     */
    @WebMethod
    @WebResult(name = "findByIdResponse", targetNamespace = "http://employee.services", partName = "findByIdResponse")
    public FindByIdResponse findById(
        @WebParam(name = "findByIdRequest", targetNamespace = "http://employee.services", partName = "findByIdRequest")
        FindByIdRequest findByIdRequest);

}
